### ISSUE TITLE
C++ Project Manager's Roadmap

### ISSUE THREAD

**Issue by Maou-Shimazu** [Cpp-Project-Manager/Cpp-Project-Manager#88]
- [x] Generating C/C++ files
- [x] Commands for opening and removing projects
- [x] Support for g++ and clang++
- [x] Active build/run system 
- * [ ] C build/run support
- * [ ] C/C++ Smart Object file compilation
- [ ] External lib support
- [ ] Code formatting command
- [ ] Linter Integration
- [ ] Package management
* - [ ] Caching
* - [ ] Frontend
* - - [ ] Versioning
* - - [ ] Documentation
* - - [ ] User Interface
* - [ ] Backend
* - - [ ] User system
* - - [ ] Git integration
* - * - [ ] Custom ignore
* - [ ] Automated package compilation
